Added additional logging for proxy container command

diff --git a/.github/workflows/GitHub-Workflow-Validation-Checks_RGCLONE.yml b/.github/workflows/GitHub-Workflow-Validation-Checks_RGCLONE.yml
--- a/.github/workflows/GitHub-Workflow-Validation-Checks_RGCLONE.yml
+++ b/.github/workflows/GitHub-Workflow-Validation-Checks_RGCLONE.yml
@@ -96,13 +96,14 @@ jobs:
           RGCLONE_API_ENDPOINT: ${{ secrets.RGCLONE_API_ENDPOINT }}
           RGCLONE_ACCESS_TOKEN: ${{ secrets.RGCLONE_ACCESS_TOKEN }}
         run: |
+          # Kill any pending RGClone processes
+          echo "Killing any pending RGClone processes"
+          pkill -f rgclone || true  # the `|| true` ensures the script doesn't fail if no process is found
+
           # Create Data Container Proxy
-          echo "Kill any pending RGClone Processes"
-          tskill rgclone
-          
           echo "Creating Data Container Proxy"
-          
-          rgclone proxy dc "$DATA_CONTAINER_NAME" -p "$PROXY_PORT" &
+          rgclone proxy dc "$DATA_CONTAINER_NAME" -p "$PROXY_PORT" &  # Run the proxy in the background
+
           echo "RGClone Proxy Enabled"
 
   Validate-Flyway-Pipeline:
